//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMstBranch
    {
        public int BranchUno { get; set; }
        public string BrandName { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public bool Active { get; set; }
        public string Location { get; set; }
    }
}
